import {
  validateManifestOptions,
  validateManifestVersion,
  validateOptionsWithImages,
  validateOutputDirectoryOption,
  validateRestoreImageOptions,
} from "./validators";

describe("validators", () => {
  test("validateOptionsWithImages accepts non-empty arrays", () => {
    const options = { images: ["a"] };
    expect(validateOptionsWithImages(options, "test")).toBe(options);
  });

  test("validateOptionsWithImages rejects empty arrays", () => {
    expect(() => validateOptionsWithImages({ images: [] }, "test")).toThrow(
      "[test] images must be a non-empty array.",
    );
  });

  test("validateOutputDirectoryOption requires outputDir", () => {
    expect(() =>
      validateOutputDirectoryOption({ outputDir: "" }, "test"),
    ).toThrow("[test] outputDir is required and must be a string.");
  });

  test("validateManifestOptions requires manifest or manifestData", () => {
    expect(() => validateManifestOptions({}, "restore")).toThrow(
      "[restore] Either manifest or manifestData is required.",
    );
  });

  describe("validateManifestVersion", () => {
    test.each(["0.3.0", "0.3.1", "0.4.0", "1.0.0", "0.3.0-beta.1"])(
      "accepts manifests generated by v%s",
      (version) => {
        expect(() => validateManifestVersion({ version })).not.toThrow();
      },
    );

    test.each([
      "0.2.9",
      "0.2.0",
      "0.1.0",
      "0.0.1",
      "0.0.0",
      "0.3",
      "invalid",
      "",
    ])("rejects manifests generated by v%s", (version) => {
      expect(() => validateManifestVersion({ version })).toThrow(
        "pixzle v0.2.x or older is no longer supported for restore. Please restore this manifest with pixzle v0.2.x.",
      );
    });
  });

  test("validateRestoreImageOptions validates single-image restore input", () => {
    const options = {
      image: "image.png",
      blockSize: 8,
      seed: "123",
      imageInfo: { w: 10, h: 10 },
    };

    expect(validateRestoreImageOptions(options, "restoreImage")).toBe(options);
  });

  test("validateRestoreImageOptions accepts string seed", () => {
    const options = {
      image: "image.png",
      blockSize: 8,
      seed: "manifest-id-seed",
      imageInfo: { w: 10, h: 10 },
    };

    expect(validateRestoreImageOptions(options, "restoreImage")).toBe(options);
  });
});
